#!/usr/bin/env bash
# This script connects to a server using SSH and a private key

# Use ssh with single-character flags:
# -i: Specify the private key file
# -o: Specify options (StrictHostKeyChecking=no to avoid host key prompts)
ssh -i ~/.ssh/school -o StrictHostKeyChecking=no ubuntu@8.8.8.8
