#!/usr/bin/env bash

# Check if 4 arguments are passed
if [ $# -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the arguments to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Transfer the file using scp
scp -i $SSH_KEY_PATH -o StrictHostKeyChecking=no $FILE_PATH $USERNAME@$SERVER_IP:~/

echo "File transferred successfully."
